name: optimesh_flutter_web
description: Flutter Web client for the OptiMesh distributed browser compute platform.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
